### ISSUE TITLE
Dynamically handling component properties example

### ISSUE THREAD

**Issue by michshat** [calmm-js/kefir.react.native#1]
Thank you for this lib ... it makes it very easy to work with (well at first glance) :) 

Question:
Let's say there is an `input` and whenever there is a validation error, the `.error` class needs to be assigned to the `style` property.

```
<K.TextInput 
                style={styles[item.lens(M.SUM.error).get()]}            
                defaultValue={item.lens(M.SUM.a).get().toString()}   
                onChange={(event) => item.lens(M.SUM.a).set(event.nativeEvent.text)}         
              />
```

```
const styles = StyleSheet.create({
error: {
    backgroundColor: 'red',
    height: 40, 
    borderColor: 'gray', 
    borderWidth: 1
  },
```

```
import * as L from "partial.lenses"
import * as R from "ramda"

export const mock = {a: 0, b: 0}

export const SUM = {
  augment: L.augment({
    c: ({a, b}) => parseInt(a) + parseInt(b) ,
    error: ({a, b}) => parseInt(a) == 3 ? 'error' : 'success'   
  }), 
  error: "error",
  c: "c",
  a: "a",
  b: "b"
}
```

I looked at kral examples https://github.com/calmm-js/kral-examples/tree/master/src - but haven't figured it out yet. Any idea?

**Comment by polytypic** [comment]
Instead of using [`get`](https://github.com/calmm-js/kefir.atom#atomget) to access the values of atoms you should embed the observables into the VDOM.  Minimally changing what you have above, you'd do something like this:

``` js
<K.TextInput
                style={K(item.view(M.SUM.error), error => styles[error])}
                value={item.lens(M.SUM.a)}
                onChangeText={text => item.lens(M.SUM.a).set(text)}
              />
```

Have you read the [documentation](https://github.com/calmm-js/documentation/blob/master/introduction-to-calmm.md)?

**Comment by michshat** [comment]
I have read the documentation - may be not in detail - and did see the mentioning of not using `get` method too much as it affects performance, but I wasn't sure what embedding observables into the DOM meant till now :) - Thank you! Your corrected sample helped greatly - works perfectly.

Thanks again!

**Comment by polytypic** [comment]
No problem. :)

The main reason to avoid `get` is not that it would give bad performance, but that it only does an operation once in the here-and-now, so to speak.  If the input values change over time, as is typical in an UI, you need to make it so that your `get` code gets re-evaluated.  But that is what observables do for you already.  So, prefer to express computations whose inputs may change over time as observables.

**Comment by michshat** [comment]
Oh ok - thanks!

Quick question about computed properties. What this lines does `bmi: R.prop("bmi")`

> Returns a function that when supplied an object returns the indicated property of that object, if it exists.

I tried it for `SUM.c` but wasn't getting too far with it :)

``` js
import * as L from "partial.lenses"
import * as R from "ramda"

export const mock = {height: 180, weight: 80}

export const BMI = {
  augment: L.augment({
    bmi: ({height, weight}) => Math.round(weight/(height * height * 0.0001))
  }),
  bmi: R.prop("bmi"),
  height: "height",
  weight: "weight",
  classification: ({bmi}) =>
      bmi < 15   ? "bmi-underweight bmi-underweight-severely"
    : bmi < 18.5 ? "bmi-underweight"
    : bmi < 25   ? "bmi-normal"
    : bmi < 30   ? "bmi-overweight"
    : bmi < 35   ? "bmi-obese"
    : bmi < 40   ? "bmi-obese bmi-obese-severely"
    :              "bmi-obese bmi-obese-very"
}
```

**Comment by polytypic** [comment]
`R.prop(x)` just gives you a function like `o => o[x]`.  The point there is just that `bmi` need not be a lens, because it is a computed property.

**Comment by michshat** [comment]
That's very nifty - I understand it more now - especially how it is used for `classification` in the meta for `BMI`
